- name: 创建PKI目录
  file: name={{ item }} state=directory
  with_items:
  - "{{ ca_dir }}"
  - /root/.kube
  - /etc/docker

- name: 同步时间
  shell: "ntpdate 192.168.201.11"

#- name: 写入环境变量$PATH 
#  shell: "echo export PATH={{ bin_dir }}:$PATH >> /etc/profile"

- name: 下载证书工具 CFSSL
  copy: src={{ pkg_dir }}/pki-pkg/{{ item }} dest={{ bin_dir }}/{{ item }} mode=0755
  with_items:
  - cfssl
  - cfssl-certinfo
  - cfssljson

- name: 分发CA 证书
  copy: src={{ item }} dest={{ ca_dir }}/{{ item }} mode=0644
  with_items:
  - ca.pem
  - ca-key.pem
  - ca.csr
  - ca-config.json
