- name: 01.缓存ansilbe setup信息
  setup: gather_subset=min

- name: 02.删除centos默认安装
  when: ansible_distribution == "CentOS"
  yum: name={{ item }} state=absent
  with_items:
  - firewalld
  - firewalld-filesystem
  - python-firewall

- name: 03.关闭 selinux
  shell: "setenforce 0 && echo SELINUX=disabled > /etc/selinux/config"
  when: ansible_distribution == "CentOS"
  ignore_errors: true

- name: 04.创建PKI目录
  file: name={{ item }} state=directory
  with_items:
  - "{{ ca_dir }}"
  - /root/.kube
  - /etc/docker

- name: 05.同步时间
  shell: "ntpdate 192.168.201.11"

#- name: 写入环境变量$PATH 
#  shell: "echo export PATH={{ bin_dir }}:$PATH >> /etc/profile"

- name: 06.下载证书工具 CFSSL
  copy: src={{ pkg_dir }}/pki-pkg/{{ item }} dest={{ bin_dir }}/{{ item }} mode=0755
  with_items:
  - cfssl
  - cfssl-certinfo
  - cfssljson

- name: 07.分发CA 证书
  copy: src={{ item }} dest={{ ca_dir }}/{{ item }} mode=0644
  with_items:
  - ca.pem
  - ca-key.pem
  - ca.csr
  - ca-config.json
