- name: 01.缓存ansilbe setup信息
  setup: gather_subset=min

- name: 02.安装 haproxy
  yum: name=haproxy state=latest
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: 03.创建haproxy配置目录
  file: name=/etc/haproxy state=directory

- name: 04.修改centos的haproxy.service
  template: src=haproxy.service.j2 dest=/usr/lib/systemd/system/haproxy.service
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: 05.配置 haproxy
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg

- name: 06.安装 keepalived
  yum: name=keepalived state=latest
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: 07.yum安装 psmisc
  yum: name=psmisc state=latest
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: 08.创建keepalived配置目录
  file: name=/etc/keepalived state=directory

- name: 09.配置 keepalived 主节点
  template: src=keepalived.conf.j2 dest=/etc/keepalived/keepalived.conf

- name: 10.重启haproxy服务
  shell: systemctl daemon-reload && systemctl enable haproxy && systemctl restart haproxy

- name: 11.重启keepalived服务
  shell: systemctl daemon-reload && systemctl enable keepalived && systemctl restart keepalived
