- name: 创建calico 相关目录
  file: name={{ item }} state=directory
  with_items:
  - /etc/calico/ssl
  - /etc/cni/net.d

- name: 拷贝证书到calico 证书目录
  copy: src={{ ca_dir }}/{{ item }} dest=/etc/calico/ssl/{{ item }}
  with_items:
  - ca.pem
  - calico.pem
  - calico-key.pem

- name: 创建 calico 的 systemd unit 文件
  template: src=calico-node.service.j2 dest=/etc/systemd/system/calico-node.service

- name: 启动calico 服务
  shell: systemctl daemon-reload && systemctl enable calico-node && systemctl restart calico-node

- name: 下载calico cni plugins和calicoctl 客户端
  copy: src={{ pkg_dir }}/calico-pkg/{{ item }} dest={{ bin_dir }}/{{ item }} mode=0755
  with_items:
  - calico
  - calico-ipam
  - loopback
  - calicoctl

- name: 准备 calicoctl配置文件
  template: src=calicoctl.cfg.j2 dest=/etc/calico/calicoctl.cfg

- name: 准备 cni配置文件
  template: src=cni-calico.conf.j2 dest=/etc/cni/net.d/10-calico.conf
