- name: 01.下载 kube-master 二进制
  copy: src={{ pkg_dir }}/master-pkg/{{ item }} dest={{ bin_dir }}/{{ item }} mode=0755
  with_items:
  - kube-apiserver
  - kube-controller-manager
  - kube-scheduler
  - kubectl

- name: 02.创建 token.csv
  template: src=token.csv.j2 dest={{ ca_dir }}/token.csv

- name: 03.创建 basic-auth.csv
  template: src=basic-auth.csv.j2 dest={{ ca_dir }}/basic-auth.csv

- name: 04.拷贝kubernetes 证书文件
  template: src={{ ca_dir }}/{{ item }} dest={{ ca_dir }}/{{ item }}
  with_items:
  - ca.pem
  - kubernetes.pem
  - kubernetes-key.pem

- name: 05.创建kube-apiserver的systemd unit文件
  template: src=kube-apiserver.service.j2 dest=/etc/systemd/system/kube-apiserver.service

- name: 06.创建kube-controller-manager的systemd unit文件
  template: src=kube-controller-manager.service.j2 dest=/etc/systemd/system/kube-controller-manager.service

- name: 07.创建kube-scheduler的systemd unit文件
  template: src=kube-scheduler.service.j2 dest=/etc/systemd/system/kube-scheduler.service

- name: 08.刷新启动文件 daemon-reload
  shell: systemctl daemon-reload

- name: 09.开机运行mater节点服务
  shell: systemctl enable kube-apiserver kube-controller-manager kube-scheduler

- name: 10.重启Master节点服务
  tags: kube-master
  shell: systemctl restart kube-apiserver kube-controller-manager kube-scheduler
