kind: Service
apiVersion: v1
metadata: 
  name: example-app
  labels:
    tier: frontend
spec: 
  selector: 
    app: example-app 
  ports:
  - name: web
    protocol: TCP
    port: 8080
    targetPort: web
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: example-app
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: example-app
        version: 1.1.3
    spec:
      containers:
      - name: example-app 
        image: registry.chinadaas.com/prometheus/prometheus_demo_service:latest 
        ports:
        - name: web
          containerPort: 8080
          protocol: TCP
